#!/bin/bash
echo 'Make sure to have the following tools in your working directory: subfinder , httpx , neucli , bugbountyscanner'
echo "Targeting $1...."
echo 'Enumarting the subdomain'
echo "Each tool output will be found at $1.tool.E3num"
./subfinder -d $1 -o $1.subfinder.E3num
echo"Running httpx to check alive hosts"
cat $1.subfinder.E3num | ./httpx -o $1.httpx.E3num
echo "Running neucli at all alive domains"
cat $1.httpx.E3num | neucli -s "low , medium , high , critical"
